### Buscar todos as matriculas
GET http://localhost:8080/api/v1/matriculas

### Buscar matricula pelo ID
GET http://localhost:8080/api/v1/matriculas/580c1134-0409-46e9-99a5-887b8e90636f

### Inserir uma nova matricula
POST http://localhost:8080/api/v1/matriculas
Content-Type: application/json

{
  "numero": "1234",
  "data": "2023-11-12T13:42:14.792Z"
}

### Remover a matricula
DELETE  http://localhost:8080/api/v1/matriculas/580c1134-0409-46e9-99a5-887b8e90636f
Content-Type: application/json

